# Generated by Django 6.0.2 on 2026-02-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ministry', models.CharField(max_length=255)),
                ('min_income', models.FloatField()),
                ('max_income', models.FloatField()),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('category', models.CharField(choices=[('GEN', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('ALL', 'All')], max_length=10)),
                ('education_level', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
