# Generated by Django 6.0.2 on 2026-02-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='category',
            field=models.CharField(blank=True, choices=[('GEN', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS'), ('ALL', 'All')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='education_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='max_income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='min_income',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
