# Generated by Django 6.0.2 on 2026-02-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_alter_scholarship_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
