# Generated by Django 6.0.2 on 2026-02-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_alter_scholarship_amount_alter_scholarship_min_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
