# Generated by Django 6.0.2 on 2026-02-24 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_studentprofile_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='preferred_language',
        ),
    ]
